## *Sesión de retos*

### Objetivo de la Sesión 3:

* Repasar NumPy resolviendo algunos ejercicios.
* Repasar Pandas resolviendo algunos ejercicios.

### *“Trabajar en equipo, divide el trabajo y multiplica los resultados”*, Anónimo.

In [1]:
import numpy as np
import pandas as pd

# 1. NumPy

1. Muestra la versión de NumPy utilizada

In [2]:
np.version.version

'1.18.1'

2. Crear un arreglo 1D con enteros positivos aleatorios

In [3]:
arreglo = np.random.randint(100, size =100)
arreglo

array([95, 59, 11,  7, 28, 41, 62, 56, 87, 99, 79, 61, 18, 53, 14,  6, 81,
       86, 28, 21,  2, 98, 26, 29, 13, 20, 25, 37, 32, 35,  4, 28, 51, 13,
       77, 52, 94, 33, 71,  2, 11, 37, 95, 39, 25, 21, 53, 85, 11, 18, 15,
       67, 18, 90,  0, 99, 62, 89, 27,  0, 74, 72,  0, 53, 17, 96, 23, 65,
       98, 74, 61, 98, 68, 12, 62,  3, 47, 73, 99, 76, 18, 49, 20, 89, 59,
       11, 96, 76, 73, 25, 14, 61, 46, 23, 70, 94, 19, 84,  2, 80])

3. Crear un arreglo booleano

In [4]:
arreglo2 = np.array([True,False,False,True,False,False,True,False,False], dtype=bool)
arreglo2


array([ True, False, False,  True, False, False,  True, False, False])

4. Extraer los items que sean divisibles en 3.

In [5]:
#opcion1
lista1 = []
for i in arreglo:
    if i %3 == 0:
        lista1.append(i) 
print(lista1) 

[87, 99, 18, 6, 81, 21, 51, 33, 39, 21, 18, 15, 18, 90, 0, 99, 27, 0, 72, 0, 96, 12, 3, 99, 18, 96, 84]


In [6]:
#opcion 2

arreglo [arreglo %3 == 0]


array([87, 99, 18,  6, 81, 21, 51, 33, 39, 21, 18, 15, 18, 90,  0, 99, 27,
        0, 72,  0, 96, 12,  3, 99, 18, 96, 84])

5. Convierte el arreglo booleano de 1D a 2D con tres filas (*reshape*)

In [7]:
print(np.reshape(arreglo2,[3,3],order ='C'))


[[ True False False]
 [ True False False]
 [ True False False]]


6. Obtén los items comunes entre dos arreglos

In [8]:
arr2 = np.random.randint(100, size =100)
arr3 = np.random.randint(100, size =100)
print( arr2 == arr3)
print(arr2 [arr2 == arr3])

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False]
[]


7. Extrae los números del vector creado en el ejercicio 2 que esten a dos números de distancia del valor promedio del arreglo.

In [71]:
r = arreglo.mean()
arreglo == r
r2 = r+2
s2 = r-2
a1 = np.logical_and(arreglo>=s2, arreglo<=r2)
at =arreglo[a1]
print(at)

[47 49 46]


8. Muestra solo 3 decimales en un vector.

In [10]:
arr3 = [1/9,1/8,1/7]
arr3
print(np.round(arr3,3))

[0.111 0.125 0.143]


9. Crea una matriz de 3x3 con los valores del 0 a 8

In [11]:
ar = np.arange(9)
print(np.reshape(ar,[3,3],order ='C'))


[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Del siguiente areglo [1,2,0,0,4,] encuentra los índices donde los elementos sean diferente a cero.

In [12]:
array=np.array([1,2,0,0,4])
[np.nonzero(array)]

[(array([0, 1, 4], dtype=int64),)]

11. Crea un vector aleatorio de 30 elementos y encuentra la media.

In [13]:
alea = np.random.randint(30, size =100)
print(alea.mean())

14.89


12. Crea un arreglo 2D con 1 en los bordes y 0 dentro. Por ejemplo:
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1

In [14]:
prim = np.array([1,1,1,1])
seg = np.array([1,0,0,1])
ter = np.array([1,0,0,1])
cuar = np.array([1,1,1,1])
res = np.vstack((prim,seg,ter,cuar))
res

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

13. ¿Cuál es el resultado de la siguiente expresión?

`0 * np.nan`

`np.nan == np.nan`

`np.inf > np.nan`

`np.nan - np.nan`

`np.nan in set([np.nan])`

`0.3 == 3 * 0.1`

In [15]:
0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1

False


14. Crea una matriz de 5x5 con valores 1, 2, 3, 4 justo después de la diagonal.

In [16]:
mat= np.random.randint(0,10,(5,5))
diag=np.arange(4)
mat[diag,diag+1] = [1,2,3,4]
mat

array([[3, 1, 6, 7, 1],
       [1, 2, 2, 8, 1],
       [8, 2, 8, 3, 5],
       [0, 2, 3, 8, 4],
       [8, 5, 9, 3, 4]])

15. Normaliza una matriz aleatoria de 5x5

In [17]:

prim = np.array([1,2,4,8,9])
seg = np.array([7,8,9,6,4])
ter = np.array([9,8,6,5,7])
cuar = np.array([8,5,2,3,6])
res = np.vstack((prim,seg,ter,cuar))
res
np.random.normal(res)

array([[2.40201321, 3.30143324, 5.35529406, 7.50292205, 9.01515661],
       [8.459345  , 8.75280254, 7.44808324, 5.10491022, 2.91629507],
       [9.78215687, 9.20115882, 6.90911976, 5.01233062, 6.82703216],
       [5.45272998, 5.90640349, 2.51977432, 3.29553407, 5.12218837]])

# 2. Pandas

1. Imprime toda la información de versión de las librerias que necesita la biblioteca de pangas.

In [18]:
pip list

Package                            Version            
---------------------------------- -------------------
alabaster                          0.7.12             
anaconda-client                    1.7.2              
anaconda-project                   0.8.3              
asn1crypto                         1.3.0              
astroid                            2.3.3              
astropy                            4.0                
atomicwrites                       1.3.0              
attrs                              19.3.0             
Babel                              2.8.0              
backcall                           0.1.0              
backports.os                       0.1.1              
backports.shutil-get-terminal-size 1.0.0              
beautifulsoup4                     4.8.2              
bitarray                           1.2.1              
bkcharts                           0.2                
bleach                             3.1.0              
bokeh     

Considera el siguiente diccionario y lista.


```
data = {
     'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
     'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
     'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
     'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

2. Crea un DataFrame con el diccionario *data* que tenga como índices los valores de la lista *labels*.

In [19]:
data = {
     'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
     'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
     'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
     'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}
labels =['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
s1=pd.DataFrame(data, index=labels)
print(s1)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


3. Muestra una descripción o información básica acerca del DataFrame y sus datos. (Pista: existe una función que lo muestra).

In [20]:
s1.info

<bound method DataFrame.info of   animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no>

4. Regresa las primeras 3 filas del DataFrame

In [21]:
pd.DataFrame(s1.iloc[0:3])

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

5. Cambia el nombre de las columnas por:


*   Animal
*   Edad
*   Visitas
*   Prioridad



In [22]:
s1.columns =['Animal','Edad','Visitas','Prioridad']

6. Muestra solo la columna "animal" and "age". ¿Esto es posible? Si no es posible, ¿qué debería ser?

In [23]:
#no nos deja con s1['Animal','Edad']
#por lo que tendriamos que pedirlas separadas y despues juntarlas talves
s1.loc[:, ['Animal', 'Edad']] 

Animal  Edad
a    cat   2.5
b    cat   3.0
c  snake   0.5
d    dog   NaN
e    dog   5.0
f    cat   2.0
g  snake   4.5
h    cat   NaN
i    dog   7.0
j    dog   3.0

7. Selecciona solo las filas donde el número de visitas sea mayor que 3.

In [24]:
#no hay
s1[s1['Visitas']>3]

Empty DataFrame
Columns: [Animal, Edad, Visitas, Prioridad]
Index: []

8. ¿Cuáles son las filas donde la edad es NaN?

In [25]:
s1.index[s1.isnull().any(axis=1)]

Index(['d', 'h'], dtype='object')

9. ¿Qué animales tienen una edad entre 2 y 4 años?

In [26]:
s1[s1['Edad']>=2]

Animal  Edad  Visitas Prioridad
a    cat   2.5        1       yes
b    cat   3.0        3       yes
e    dog   5.0        2        no
f    cat   2.0        3        no
g  snake   4.5        1        no
i    dog   7.0        2        no
j    dog   3.0        1        no

10. ¿Cuál es el total de todas las visitas?

In [27]:
s1['Visitas'].sum()

19

12. Tenemos diferentes animales, ¿cuál es el número total de cada tipo de animal?

In [28]:
s1['Animal'].value_counts()

dog      4
cat      4
snake    2
Name: Animal, dtype: int64

13. Cambia los valores de la columna Prioridad por valores booleanos, es decir:
'yes' => True 
'no' => False

In [34]:
#No estoy muy seguro de esta porque los reemplaza sin embargo si imprimo mi s1, los valores siguen siendo 'yes' y 'no'
#nose si ese era el objetivo

s1.Prioridad.replace({'yes':True,'no':False})

a     True
b     True
c    False
d     True
e    False
f    False
g    False
h     True
i    False
j    False
Name: Prioridad, dtype: bool

14. Ordena el DataFrame por la Edad en orden descendiente y después por la columna Visitas en orden ascendente.

In [33]:

s1.sort_values(['Edad', 'Visitas'], ascending=[False, True])

Animal  Edad  Visitas Prioridad
i    dog   7.0        2        no
e    dog   5.0        2        no
g  snake   4.5        1        no
j    dog   3.0        1        no
b    cat   3.0        3       yes
a    cat   2.5        1       yes
f    cat   2.0        3        no
c  snake   0.5        2        no
h    cat   NaN        1       yes
d    dog   NaN        3       yes

15. Para cada tipo de animal y cada número de visitas encuentra la edad promedio. 
(Pista: Si haz utilizado tablas pivotes, cada fila es un animal, cada columna es el número de visitas y los valores son la media de la edad).

In [43]:
table = pd.pivot_table(s1, values=['Visitas', 'Edad'], index=['Animal'],
                    columns=['Visitas'], aggfunc={'Edad': np.mean})
table


Edad          
Visitas    1    2    3
Animal                
cat      2.5  NaN  2.5
dog      3.0  6.0  NaN
snake    4.5  0.5  NaN

# 3. Retos (opcional)

- Random Walk

- Game of Life

- Imagenes

- Texto